name: totv_plus
description: ToTV+ Cinema - Netflix-Style Streaming Platform
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  
  video_player: ^2.8.6
  chewie: ^1.8.1
  wakelock_plus: ^1.2.5
  
  firebase_core: ^3.3.0
  firebase_remote_config: ^5.0.4
  firebase_analytics: ^11.2.1
  
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  
  intl: ^0.19.0
  url_launcher: ^6.3.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
