name: totv_plus
description: ToTV+ - Live TV & VOD Streaming Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # تم استبدال المكتبة هنا بالنسخة المتوافقة مع 2026
  video_player: ^2.8.1
  better_player_plus: ^1.0.0 # التعديل هنا
  chewie: ^1.7.4
  wakelock_plus: ^1.1.4
  
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  intl: ^0.18.1
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.2
  path_provider: ^2.1.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # الأصول معطلة حتى تضع الملفات في مجلداتها
  # assets:
  #   - assets/images/
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
